[package]
name = "verity-solver-website"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
verity-solver-models = { path = "../models" }
wasm-logger = "0.2"
web-sys = { version = "0.3", features = ["MouseEvent"] }
yew = { version = "0.21", features = ["csr"] }
yew-router = "0.18"