[package]
name = "verity-solver-website"
version = "0.1.0"
edition = "2021"

[dependencies]
verity-solver-models = { path = "../models" }
yew = { version = "0.21", features = ["csr"] }
yew-router = "0.18"